In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
films = '../data/film.csv'
film = pd.read_csv(films)
pd.set_option('display.max_columns', None)



film.head()

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,NaN,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,NaN,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,NaN,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,NaN,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,NaN,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42

In [5]:
film.shape

(1000, 13)

In [4]:
unique_film = film.nunique()
print(unique_film)

film_id                 1000
title                   1000
description             1000
release_year               1
language_id                1
original_language_id       0
rental_duration            5
rental_rate                3
length                   140
replacement_cost          21
rating                     5
special_features          15
last_update                1
dtype: int64

In [6]:
film.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   film_id               1000 non-null   int64
 1   title                 1000 non-null   object
 2   description           1000 non-null   object
 3   release_year          1000 non-null   int64
 4   language_id           1000 non-null   int64
 5   original_language_id  0 non-null      float64
 6   rental_duration       1000 non-null   int64
 7   rental_rate           1000 non-null   float64
 8   length                1000 non-null   int64
 9   replacement_cost      1000 non-null   float64
 10  rating                1000 non-null   object
 11  special_features      1000 non-null   object
 12  last_update           1000 non-null   object
dtypes: float64(3), int64(5), object(5)
memory usage: 495.3 KB

In [7]:
film.shape

(1000, 13)

In [8]:
film.set_index('film_id', inplace=True)

In [9]:
film.head()

,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
film_id,,,,,,,,,,,,
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,NaN,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42
2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,NaN,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42
3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,NaN,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42
4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,NaN,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42
5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,NaN,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42

In [10]:
film["release_year"] = "-0001"

In [11]:
film["release_year"].head()

film_id
1    -0001
2    -0001
3    -0001
4    -0001
5    -0001
Name: release_year, dtype: object

In [18]:
film[["language_id"]] = "Undefined"
film["language_id"].head()

film_id
1    Undefined
2    Undefined
3    Undefined
4    Undefined
5    Undefined
Name: language_id, dtype: object

In [19]:
film[["original_language_id"]] = "Undefined"
film["original_language_id"].head()

film_id
1    Undefined
2    Undefined
3    Undefined
4    Undefined
5    Undefined
Name: original_language_id, dtype: object

In [20]:
film.rename(columns={"rental_rate": "rental_price"}, inplace=True)

In [21]:
film["title"] = film["title"].str.title()
film.head()

,title,description,release_year,language_id,original_language_id,rental_duration,rental_price,length,replacement_cost,rating,special_features,last_update,original_language_id\t
film_id,,,,,,,,,,,,,
1,Academy Dinosaur,A Epic Drama of a Feminist And a Mad Scientist...,-0001,Undefined,Undefined,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2006-02-15 05:03:42,Undefined
2,Ace Goldfinger,A Astounding Epistle of a Database Administrat...,-0001,Undefined,Undefined,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2006-02-15 05:03:42,Undefined
3,Adaptation Holes,A Astounding Reflection of a Lumberjack And a ...,-0001,Undefined,Undefined,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2006-02-15 05:03:42,Undefined
4,Affair Prejudice,A Fanciful Documentary of a Frisbee And a Lumb...,-0001,Undefined,Undefined,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2006-02-15 05:03:42,Undefined
5,African Egg,A Fast-Paced Documentary of a Pastry Chef And ...,-0001,Undefined,Undefined,6,2.99,130,22.99,G,Deleted Scenes,2006-02-15 05:03:42,Undefined

In [22]:
# last_update original_language_id\t

film.drop(["last_update", "original_language_id\t"], axis=1, inplace=True)
film.head()

,title,description,release_year,language_id,original_language_id,rental_duration,rental_price,length,replacement_cost,rating,special_features
film_id,,,,,,,,,,,
1,Academy Dinosaur,A Epic Drama of a Feminist And a Mad Scientist...,-0001,Undefined,Undefined,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes"
2,Ace Goldfinger,A Astounding Epistle of a Database Administrat...,-0001,Undefined,Undefined,3,4.99,48,12.99,G,"Trailers,Deleted Scenes"
3,Adaptation Holes,A Astounding Reflection of a Lumberjack And a ...,-0001,Undefined,Undefined,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes"
4,Affair Prejudice,A Fanciful Documentary of a Frisbee And a Lumb...,-0001,Undefined,Undefined,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes"
5,African Egg,A Fast-Paced Documentary of a Pastry Chef And ...,-0001,Undefined,Undefined,6,2.99,130,22.99,G,Deleted Scenes

In [23]:
rows_with_null = film.isnull().all(axis=1)

print(rows_with_null)

film_id
1       False
2       False
3       False
4       False
5       False
        ...
996     False
997     False
998     False
999     False
1000    False
Length: 1000, dtype: bool